export enum Configuration {
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  EXPIRES_IN = 'EXPIRES_IN',
  DB_PORT = 'DB_PORT',
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
}
